apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: keycloakrealm-sample
spec:
  id: test
  realmName: test
  keycloakOwner: main
  ssoRealmName: openshift
  ssoRealmEnabled: false # new one
  ssoAutoRedirectEnabled: false # new one
  passwordPolicy:
    - type: "forceExpiredPasswordChange"
      value: "365"
    - type: "length"
      value: "8"
  realmEventConfig:
    adminEventsDetailsEnabled: false
    adminEventsEnabled: true
    enabledEventTypes:
      - UPDATE_CONSENT_ERROR
      - CLIENT_LOGIN
    eventsEnabled: true
    eventsExpiration: 15000
    eventsListeners:
      - jboss-logging
